apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: LoadBalancer # Cluster IP by default, internal IP only; NodePort still not stable as nodes are changing (create/delete)
  ports:
    - protocol: TCP
      port: 8080 # outside facing
      targetPort: 8080 # container expected port
